json.id @item_image.id
json.item_id @item_image.item_id
json.item_name @item.name
json.url @item_image.image_url
json.date @item_image.created_at
json.added_date @item_image.added_at
json.memo @item_image.memo
json.image_favorite_count @item_image.image_favorites.size
json.is_favorited @item_image.is_favorited?(@user_id)
